services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-aesirx}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-1stparty}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-aesirxanalytics}
    volumes:
      - type: volume
        source: mongo
        target: /data/db
    networks:
      - backend

  aesirx-analytics:
    image: aesirxio/analytics-1stparty:develop
    restart: always
    pull_policy: always
    volumes:
      - type: bind
        source: ./aesirx-1stparty.env
        target: /.env
    networks:
      - backend
  
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - protocol: tcp
        published: 80
        target: 80
    volumes:
      - type: bind
        source: ./proxy.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

volumes:
  mongo: {}

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
