services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-aesirx}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-1stparty}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-aesirxanalytics}
    volumes:
      - ./data/db:/data/db
    ports:
      - ${MONGO_PORT-27017}:27017
    networks:
      - backend

  aesirx-analytics:
    image: aesirxio/analytics-1stparty:develop
    platform: linux/amd64
    restart: always
    pull_policy: always
    volumes:
      - ./aesirx-1stparty.env:/.env
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT-80}:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ${SSL_CRT-./certs/ssl.crt}:/etc/nginx/ssl.crt
      - ${SSL_KEY-./certs/ssl.key}:/etc/nginx/ssl.key
    networks:
      - backend

networks:
  backend:
    driver: bridge
